run: boundary-traversal-of-binary-tree
	./boundary-traversal-of-binary-tree

boundary-traversal-of-binary-tree: boundary-traversal-of-binary-tree.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr boundary-traversal-of-binary-tree *.o *.dSYM
