run: remove-duplicates-in-sorted-array-put-duplicated-at-the-end
	./remove-duplicates-in-sorted-array-put-duplicated-at-the-end

remove-duplicates-in-sorted-array-put-duplicated-at-the-end: remove-duplicates-in-sorted-array-put-duplicated-at-the-end.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr remove-duplicates-in-sorted-array-put-duplicated-at-the-end *.o *.dSYM
