run: dp-maximum-sum-increasing-subsequence
	./dp-maximum-sum-increasing-subsequence

dp-maximum-sum-increasing-subsequence: dp-maximum-sum-increasing-subsequence.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr dp-maximum-sum-increasing-subsequence *.o *.dSYM
