run: copy-list-with-random-pointer
	./copy-list-with-random-pointer

copy-list-with-random-pointer: copy-list-with-random-pointer.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr copy-list-with-random-pointer *.o *.dSYM
