run: implement-queue-using-stacks
	./implement-queue-using-stacks

implement-queue-using-stacks: implement-queue-using-stacks.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr implement-queue-using-stacks *.o *.dSYM
