run: add-and-search-word-data-structure-design
	@./add-and-search-word-data-structure-design

add-and-search-word-data-structure-design: add-and-search-word-data-structure-design.cc
	@g++ -std=c++11 $^ -o $@
