run: remove-duplicates-from-sorted-array-ii
	./remove-duplicates-from-sorted-array-ii

remove-duplicates-from-sorted-array-ii: remove-duplicates-from-sorted-array-ii.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr remove-duplicates-from-sorted-array-ii *.o *.dSYM
