run: binary-tree-zig-zag-traverse
	./binary-tree-zig-zag-traverse

binary-tree-zig-zag-traverse: binary-tree-zig-zag-traverse.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr binary-tree-zig-zag-traverse *.o *.dSYM
