run: remove-duplicates-from-sorted-array
	./remove-duplicates-from-sorted-array

remove-duplicates-from-sorted-array: remove-duplicates-from-sorted-array.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr remove-duplicates-from-sorted-array *.o *.dSYM
