run: binary-tree-with-parent-traveral
	./binary-tree-with-parent-traveral

binary-tree-with-parent-traveral: binary-tree-with-parent-traveral.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr binary-tree-with-parent-traveral *.o *.dSYM
