run: kth-largest-element-in-an-array
	./kth-largest-element-in-an-array

kth-largest-element-in-an-array: kth-largest-element-in-an-array.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm kth-largest-element-in-an-array *.o
