run: dynamic-programming-subset-sum-problem
	./dynamic-programming-subset-sum-problem

dynamic-programming-subset-sum-problem: dynamic-programming-subset-sum-problem.cc
		g++ -g $^ -o $@
	# g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr dynamic-programming-subset-sum-problem *.o *.dSYM
