run: two-elements-whose-sum-is-closest-to-zero
	./two-elements-whose-sum-is-closest-to-zero

two-elements-whose-sum-is-closest-to-zero: two-elements-whose-sum-is-closest-to-zero.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr two-elements-whose-sum-is-closest-to-zero *.o *.dSYM
