run: serialize-and-deserialize-binary-tree
	./serialize-and-deserialize-binary-tree

serialize-and-deserialize-binary-tree: serialize-and-deserialize-binary-tree.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr serialize-and-deserialize-binary-tree *.o *.dSYM
