run: find-unique-character-in-a-string
	./find-unique-character-in-a-string

find-unique-character-in-a-string: find-unique-character-in-a-string.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr find-unique-character-in-a-string *.o *.dSYM
