run: print-binary-tree-vertical-order
	./print-binary-tree-vertical-order

print-binary-tree-vertical-order: print-binary-tree-vertical-order.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr print-binary-tree-vertical-order *.o *.dSYM
