run: const-ref-param-rvalue-arg
	./const-ref-param-rvalue-arg

const-ref-param-rvalue-arg: const-ref-param-rvalue-arg.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr const-ref-param-rvalue-arg *.o *.dSYM
