run: median-of-two-sorted-arrays
	./median-of-two-sorted-arrays

median-of-two-sorted-arrays: median-of-two-sorted-arrays.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr median-of-two-sorted-arrays *.o *.dSYM
