run: kth-smallest-element-in-a-bst
	./kth-smallest-element-in-a-bst

kth-smallest-element-in-a-bst: kth-smallest-element-in-a-bst.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr kth-smallest-element-in-a-bst *.o *.dSYM
