run: implement-stack-using-queues
	./implement-stack-using-queues

implement-stack-using-queues: implement-stack-using-queues.cc
	g++ -std=c++11 -g $^ -o $@

clean:
	rm -fr implement-stack-using-queues *.o *.dSYM
